In [12]:
import numpy as np 

In [13]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])
a2


array([ 6,  7,  8,  9, 10])

In [14]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [15]:
a1-a2

array([-5, -5, -5, -5, -5])

In [16]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [17]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [10]:
a1//a2

array([0, 0, 0, 0, 0])

In [10]:
import numpy as np

l = [10,20,30,40]
arr=np.array(l)

In [11]:
l=[10,20,30,40]
arr=np.array(l)

In [12]:
arr+10

array([20, 30, 40, 50])

In [13]:
arr2=np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [14]:
arr2+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [15]:
#deep and shallow copy

In [16]:
a=np.arange(1,21)
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [18]:
slice=a[:5]
slice=slice *10
slice

array([10, 20, 30, 40, 50])

In [19]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [20]:
#matrix operation

In [21]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])


In [22]:
A

array([[1, 2],
       [3, 4]])

In [23]:
B

array([[5, 6],
       [7, 8]])

In [24]:
A *B

array([[ 5, 12],
       [21, 32]])

In [25]:
A@B

array([[19, 22],
       [43, 50]])

In [26]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [27]:
A.T

array([[1, 3],
       [2, 4]])

In [28]:
#ADVANCE ARRAY MANIPULATION


In [29]:
#Stacking Array

In [32]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [33]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [34]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [37]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [38]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [41]:
a=np.vsplit(c,4)

In [44]:
for i in a:
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
