In [1]:
import numpy as np

In [3]:
import numpy as np
data=np.array([
    [18,85,78],   #student1
    [19,92,88],   #student2
    [17,76,95],   #student3
    [18,65,70],   #student4
    [20,90,85]    #student5
])

In [4]:
data.shape

(5, 3)

In [6]:
#find the average age of student
np.mean(data[:,0])

np.float64(18.4)

In [7]:
#extract math marks of all student 
data[:,1]

array([85, 92, 76, 65, 90])

In [8]:
#find the highst science mark
np.max(data[:,2])

np.int64(95)

In [11]:
#get detail of the student who scored more than 90 in math
data[data[:,1]>90]

array([[19, 92, 88]])

In [12]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [13]:
#increase math mark of all student by 5.
data[:,1]+=5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [17]:
#find how many student are younger than 19
len(data[data[:,0]<19])

3

In [18]:
#calculate the average mark in each subject (column-wise mean).
np.mean(data[:,1:],axis=0)

array([86.6, 83.2])

In [19]:
#Get data of student who scored at least 80 in both subjects.
data[(data[:,1]>=80) & (data[:,2]>=80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [25]:
#Replace all science mark <75 with 0
data[:,2][data[:,2]<75]=0
data


array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [ 0,  0,  0],
       [20, 95, 85]])